before_install:
  - date
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - cd ${HOME}
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get -qq -y update
  - sudo apt-get -qq -y install gcc-arm-none-eabi libgmp-dev libgc-dev
  # Download ATS2
  - git clone git://git.code.sf.net/p/ats2-lang/code ATS2-srcfrg
  # Setup ATS2 contrib
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
  # Build ATS2
  - export PATSHOME=${HOME}/ATS2-srcfrg
  - export PATH=${PATH}:${PATSHOME}/bin
  - cd ${PATSHOME} && ./configure && make
script:
  - cd ${TRAVIS_BUILD_DIR}
  - make
after_script:
  - date
